[package]
name = "hello-rust"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "1.0.0"
mysql = "20.1.0"
json = "0.12.4"
actix-web = "3"